import type { BroadcastTheme } from "@/types/broadcast"
import { DESIGN_WIDTH, DESIGN_HEIGHT } from "@/lib/canvas-constants"

const baseTheme: Omit<
  BroadcastTheme,
  | "id"
  | "name"
  | "category"
  | "background"
  | "verseText"
  | "reference"
  | "layout"
  | "transition"
  | "textBox"
> = {
  builtin: true,
  pinned: false,
  createdAt: 0,
  updatedAt: 0,
  resolution: { width: DESIGN_WIDTH, height: DESIGN_HEIGHT },
  elements: [],
  layerOrder: ["textArea", "verse", "reference"],
  verseNumbers: {
    visible: true,
    fontSize: 14,
    color: "#ffffff",
    superscript: true,
  },
}

const CLASSIC_DARK: BroadcastTheme = {
  ...baseTheme,
  id: "builtin-classic-dark",
  name: "Classic Dark",
  category: "scripture",
  background: {
    type: "gradient",
    color: "#1a1a3e",
    gradient: {
      type: "radial",
      angle: 0,
      stops: [
        { color: "#1a1a3e", position: 0 },
        { color: "#0a0a1a", position: 100 },
      ],
    },
    image: null,
    video: null,
  },
  textBox: {
    enabled: false,
    color: "#000000",
    opacity: 0,
    borderRadius: 0,
    padding: 0,
  },
  verseText: {
    fontFamily: "Source Serif 4 Variable",
    fontSize: 72,
    fontWeight: 400,
    color: "#ffffff",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    lineHeight: 1.5,
    letterSpacing: 0,
    shadow: null,
    outline: null,
  },
  verseNumbers: {
    visible: true,
    fontSize: 20,
    color: "#d4a574",
    superscript: true,
  },
  reference: {
    fontFamily: "Geist Variable",
    fontSize: 48,
    fontWeight: 500,
    color: "#d4a574",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    uppercase: true,
    letterSpacing: 2,
    lineHeight: 1.4,
    position: "above",
    shadow: null,
    outline: null,
  },
  layout: {
    anchor: "center",
    offsetX: 0,
    offsetY: 0,
    padding: { top: 60, right: 80, bottom: 60, left: 80 },
    textAlign: "center",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 80,
    textAreaHeight: 80,
    referenceGap: 32,
  },
  transition: {
    type: "fade",
    duration: 500,
    easing: "ease-in-out",
    direction: "up",
  },
}

const MODERN_LIGHT: BroadcastTheme = {
  ...baseTheme,
  id: "builtin-modern-light",
  name: "Modern Light",
  category: "general",
  background: {
    type: "solid",
    color: "#f5f5f0",
    gradient: null,
    image: null,
    video: null,
  },
  textBox: {
    enabled: false,
    color: "#000000",
    opacity: 0,
    borderRadius: 0,
    padding: 0,
  },
  verseText: {
    fontFamily: "Geist Variable",
    fontSize: 68,
    fontWeight: 400,
    color: "#1a1a1a",
    horizontalAlign: "left",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    lineHeight: 1.6,
    letterSpacing: 0,
    shadow: null,
    outline: null,
  },
  verseNumbers: {
    visible: true,
    fontSize: 18,
    color: "#666666",
    superscript: true,
  },
  reference: {
    fontFamily: "Geist Variable",
    fontSize: 45,
    fontWeight: 500,
    color: "#666666",
    horizontalAlign: "left",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    uppercase: false,
    letterSpacing: 0,
    lineHeight: 1.4,
    position: "above",
    shadow: null,
    outline: null,
  },
  layout: {
    anchor: "center",
    offsetX: 0,
    offsetY: 0,
    padding: { top: 60, right: 80, bottom: 60, left: 80 },
    textAlign: "left",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 80,
    textAreaHeight: 80,
    referenceGap: 30,
  },
  transition: {
    type: "slide",
    duration: 400,
    easing: "ease-out",
    direction: "up",
  },
}

const BROADCAST_OVERLAY: BroadcastTheme = {
  ...baseTheme,
  id: "builtin-broadcast-overlay",
  name: "Broadcast Overlay",
  category: "overlay",
  background: {
    type: "transparent",
    color: "transparent",
    gradient: null,
    image: null,
    video: null,
  },
  textBox: {
    enabled: true,
    color: "#000000",
    opacity: 0.7,
    borderRadius: 12,
    padding: 24,
  },
  verseText: {
    fontFamily: "Geist Variable",
    fontSize: 64,
    fontWeight: 500,
    color: "#ffffff",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    lineHeight: 1.5,
    letterSpacing: 0,
    shadow: { color: "rgba(0,0,0,0.8)", blur: 8, x: 0, y: 2 },
    outline: null,
  },
  verseNumbers: {
    visible: true,
    fontSize: 18,
    color: "#fbbf24",
    superscript: true,
  },
  reference: {
    fontFamily: "Geist Variable",
    fontSize: 43,
    fontWeight: 600,
    color: "#fbbf24",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    uppercase: false,
    letterSpacing: 1,
    lineHeight: 1.4,
    position: "below",
    shadow: null,
    outline: null,
  },
  layout: {
    anchor: "bottom-center",
    offsetX: 0,
    offsetY: 0,
    padding: { top: 40, right: 60, bottom: 40, left: 60 },
    textAlign: "center",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 90,
    textAreaHeight: 40,
    referenceGap: 24,
  },
  transition: {
    type: "fade",
    duration: 300,
    easing: "ease-in-out",
    direction: "up",
  },
}

const WORSHIP_NIGHT: BroadcastTheme = {
  ...baseTheme,
  id: "builtin-worship-night",
  name: "Worship Night",
  category: "song",
  background: {
    type: "gradient",
    color: "#0f0c29",
    gradient: {
      type: "linear",
      angle: 160,
      stops: [
        { color: "#0f0c29", position: 0 },
        { color: "#302b63", position: 50 },
        { color: "#24243e", position: 100 },
      ],
    },
    image: null,
    video: null,
  },
  textBox: {
    enabled: false,
    color: "#000000",
    opacity: 0,
    borderRadius: 0,
    padding: 0,
  },
  verseText: {
    fontFamily: "Geist Variable",
    fontSize: 80,
    fontWeight: 700,
    color: "#ffffff",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "uppercase",
    textDecoration: "none",
    lineHeight: 1.3,
    letterSpacing: 2,
    shadow: { color: "rgba(0,0,0,0.6)", blur: 12, x: 0, y: 4 },
    outline: null,
  },
  verseNumbers: {
    visible: false,
    fontSize: 16,
    color: "#ffffff",
    superscript: true,
  },
  reference: {
    fontFamily: "Geist Variable",
    fontSize: 36,
    fontWeight: 400,
    color: "#a78bfa",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    uppercase: false,
    letterSpacing: 3,
    lineHeight: 1.4,
    position: "below",
    shadow: null,
    outline: null,
  },
  layout: {
    anchor: "center",
    offsetX: 0,
    offsetY: 0,
    padding: { top: 80, right: 100, bottom: 80, left: 100 },
    textAlign: "center",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 85,
    textAreaHeight: 70,
    referenceGap: 36,
  },
  transition: {
    type: "fade",
    duration: 400,
    easing: "ease-in-out",
    direction: "up",
  },
}

const HYMNAL: BroadcastTheme = {
  ...baseTheme,
  id: "builtin-hymnal",
  name: "Hymnal",
  category: "song",
  background: {
    type: "solid",
    color: "#1c1917",
    gradient: null,
    image: null,
    video: null,
  },
  textBox: {
    enabled: false,
    color: "#000000",
    opacity: 0,
    borderRadius: 0,
    padding: 0,
  },
  verseText: {
    fontFamily: "Georgia",
    fontSize: 72,
    fontWeight: 400,
    color: "#fef3c7",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    lineHeight: 1.6,
    letterSpacing: 0,
    shadow: null,
    outline: null,
  },
  verseNumbers: {
    visible: false,
    fontSize: 16,
    color: "#fef3c7",
    superscript: true,
  },
  reference: {
    fontFamily: "Georgia",
    fontSize: 40,
    fontWeight: 400,
    color: "#92400e",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    uppercase: false,
    letterSpacing: 1,
    lineHeight: 1.4,
    position: "below",
    shadow: null,
    outline: null,
  },
  layout: {
    anchor: "center",
    offsetX: 0,
    offsetY: 0,
    padding: { top: 60, right: 120, bottom: 60, left: 120 },
    textAlign: "center",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 75,
    textAreaHeight: 75,
    referenceGap: 28,
  },
  transition: {
    type: "fade",
    duration: 600,
    easing: "ease-in-out",
    direction: "up",
  },
}

const PRAISE_BOLD: BroadcastTheme = {
  ...baseTheme,
  id: "builtin-praise-bold",
  name: "Praise Bold",
  category: "song",
  background: {
    type: "gradient",
    color: "#0a0a0a",
    gradient: {
      type: "radial",
      angle: 0,
      stops: [
        { color: "#1a1a2e", position: 0 },
        { color: "#0a0a0a", position: 100 },
      ],
    },
    image: null,
    video: null,
  },
  textBox: {
    enabled: false,
    color: "#000000",
    opacity: 0,
    borderRadius: 0,
    padding: 0,
  },
  verseText: {
    fontFamily: "Geist Variable",
    fontSize: 88,
    fontWeight: 800,
    color: "#ffffff",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "uppercase",
    textDecoration: "none",
    lineHeight: 1.2,
    letterSpacing: -1,
    shadow: { color: "rgba(59,130,246,0.3)", blur: 40, x: 0, y: 0 },
    outline: null,
  },
  verseNumbers: {
    visible: false,
    fontSize: 16,
    color: "#ffffff",
    superscript: true,
  },
  reference: {
    fontFamily: "Geist Variable",
    fontSize: 32,
    fontWeight: 500,
    color: "#60a5fa",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "uppercase",
    textDecoration: "none",
    uppercase: true,
    letterSpacing: 6,
    lineHeight: 1.4,
    position: "below",
    shadow: null,
    outline: null,
  },
  layout: {
    anchor: "center",
    offsetX: 0,
    offsetY: 0,
    padding: { top: 80, right: 80, bottom: 80, left: 80 },
    textAlign: "center",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 90,
    textAreaHeight: 70,
    referenceGap: 40,
  },
  transition: {
    type: "scale",
    duration: 350,
    easing: "ease-out",
    direction: "up",
  },
}

const PARCHMENT: BroadcastTheme = {
  ...baseTheme,
  id: "builtin-parchment",
  name: "Parchment",
  category: "scripture",
  background: {
    type: "solid",
    color: "#f5f0e8",
    gradient: null,
    image: null,
    video: null,
  },
  textBox: {
    enabled: false,
    color: "#000000",
    opacity: 0,
    borderRadius: 0,
    padding: 0,
  },
  verseText: {
    fontFamily: "Georgia",
    fontSize: 66,
    fontWeight: 400,
    color: "#292524",
    horizontalAlign: "left",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    lineHeight: 1.7,
    letterSpacing: 0,
    shadow: null,
    outline: null,
  },
  verseNumbers: {
    visible: true,
    fontSize: 18,
    color: "#78716c",
    superscript: true,
  },
  reference: {
    fontFamily: "Georgia",
    fontSize: 42,
    fontWeight: 700,
    color: "#78716c",
    horizontalAlign: "left",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    uppercase: false,
    letterSpacing: 0,
    lineHeight: 1.4,
    position: "above",
    shadow: null,
    outline: null,
  },
  layout: {
    anchor: "center",
    offsetX: 0,
    offsetY: 0,
    padding: { top: 80, right: 120, bottom: 80, left: 120 },
    textAlign: "left",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 75,
    textAreaHeight: 80,
    referenceGap: 24,
  },
  transition: {
    type: "fade",
    duration: 500,
    easing: "ease-in-out",
    direction: "up",
  },
}

const SCRIPTURE_FOCUS: BroadcastTheme = {
  ...baseTheme,
  id: "builtin-scripture-focus",
  name: "Scripture Focus",
  category: "scripture",
  background: {
    type: "gradient",
    color: "#0c4a6e",
    gradient: {
      type: "linear",
      angle: 180,
      stops: [
        { color: "#0c4a6e", position: 0 },
        { color: "#082f49", position: 100 },
      ],
    },
    image: null,
    video: null,
  },
  textBox: {
    enabled: false,
    color: "#000000",
    opacity: 0,
    borderRadius: 0,
    padding: 0,
  },
  verseText: {
    fontFamily: "Source Serif 4 Variable",
    fontSize: 70,
    fontWeight: 400,
    color: "#e0f2fe",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    lineHeight: 1.6,
    letterSpacing: 0,
    shadow: null,
    outline: null,
  },
  verseNumbers: {
    visible: true,
    fontSize: 20,
    color: "#7dd3fc",
    superscript: true,
  },
  reference: {
    fontFamily: "Geist Variable",
    fontSize: 44,
    fontWeight: 600,
    color: "#7dd3fc",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    uppercase: true,
    letterSpacing: 3,
    lineHeight: 1.4,
    position: "above",
    shadow: null,
    outline: null,
  },
  layout: {
    anchor: "center",
    offsetX: 0,
    offsetY: 0,
    padding: { top: 60, right: 100, bottom: 60, left: 100 },
    textAlign: "center",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 80,
    textAreaHeight: 80,
    referenceGap: 30,
  },
  transition: {
    type: "fade",
    duration: 450,
    easing: "ease-in-out",
    direction: "up",
  },
}

const SERMON_CLEAN: BroadcastTheme = {
  ...baseTheme,
  id: "builtin-sermon-clean",
  name: "Sermon Clean",
  category: "sermon",
  background: {
    type: "solid",
    color: "#18181b",
    gradient: null,
    image: null,
    video: null,
  },
  textBox: {
    enabled: false,
    color: "#000000",
    opacity: 0,
    borderRadius: 0,
    padding: 0,
  },
  verseText: {
    fontFamily: "Geist Variable",
    fontSize: 64,
    fontWeight: 400,
    color: "#e4e4e7",
    horizontalAlign: "left",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    lineHeight: 1.6,
    letterSpacing: 0,
    shadow: null,
    outline: null,
  },
  verseNumbers: {
    visible: true,
    fontSize: 16,
    color: "#71717a",
    superscript: true,
  },
  reference: {
    fontFamily: "Geist Variable",
    fontSize: 38,
    fontWeight: 600,
    color: "#a1a1aa",
    horizontalAlign: "left",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    uppercase: true,
    letterSpacing: 2,
    lineHeight: 1.4,
    position: "above",
    shadow: null,
    outline: null,
  },
  layout: {
    anchor: "center",
    offsetX: 0,
    offsetY: 0,
    padding: { top: 60, right: 100, bottom: 60, left: 100 },
    textAlign: "left",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 80,
    textAreaHeight: 80,
    referenceGap: 24,
  },
  transition: {
    type: "slide",
    duration: 350,
    easing: "ease-out",
    direction: "up",
  },
}

const SERMON_FULLSCREEN: BroadcastTheme = {
  ...baseTheme,
  id: "builtin-sermon-fullscreen",
  name: "Sermon Fullscreen",
  category: "sermon",
  background: {
    type: "gradient",
    color: "#111827",
    gradient: {
      type: "radial",
      angle: 0,
      stops: [
        { color: "#1f2937", position: 0 },
        { color: "#111827", position: 100 },
      ],
    },
    image: null,
    video: null,
  },
  textBox: {
    enabled: false,
    color: "#000000",
    opacity: 0,
    borderRadius: 0,
    padding: 0,
  },
  verseText: {
    fontFamily: "Geist Variable",
    fontSize: 76,
    fontWeight: 500,
    color: "#f9fafb",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    lineHeight: 1.5,
    letterSpacing: 0,
    shadow: null,
    outline: null,
  },
  verseNumbers: {
    visible: true,
    fontSize: 18,
    color: "#9ca3af",
    superscript: true,
  },
  reference: {
    fontFamily: "Geist Variable",
    fontSize: 42,
    fontWeight: 500,
    color: "#6b7280",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    uppercase: false,
    letterSpacing: 1,
    lineHeight: 1.4,
    position: "below",
    shadow: null,
    outline: null,
  },
  layout: {
    anchor: "center",
    offsetX: 0,
    offsetY: 0,
    padding: { top: 80, right: 80, bottom: 80, left: 80 },
    textAlign: "center",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 85,
    textAreaHeight: 80,
    referenceGap: 32,
  },
  transition: {
    type: "fade",
    duration: 400,
    easing: "ease-in-out",
    direction: "up",
  },
}

const LOWER_THIRD_DARK: BroadcastTheme = {
  ...baseTheme,
  id: "builtin-lower-third-dark",
  name: "Lower Third Dark",
  category: "overlay",
  background: {
    type: "transparent",
    color: "transparent",
    gradient: null,
    image: null,
    video: null,
  },
  textBox: {
    enabled: true,
    color: "#000000",
    opacity: 0.85,
    borderRadius: 8,
    padding: 20,
  },
  verseText: {
    fontFamily: "Geist Variable",
    fontSize: 56,
    fontWeight: 500,
    color: "#ffffff",
    horizontalAlign: "left",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    lineHeight: 1.5,
    letterSpacing: 0,
    shadow: null,
    outline: null,
  },
  verseNumbers: {
    visible: false,
    fontSize: 14,
    color: "#ffffff",
    superscript: true,
  },
  reference: {
    fontFamily: "Geist Variable",
    fontSize: 36,
    fontWeight: 600,
    color: "#fbbf24",
    horizontalAlign: "left",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    uppercase: true,
    letterSpacing: 2,
    lineHeight: 1.4,
    position: "above",
    shadow: null,
    outline: null,
  },
  layout: {
    anchor: "bottom-left",
    offsetX: 5,
    offsetY: -5,
    padding: { top: 20, right: 40, bottom: 20, left: 40 },
    textAlign: "left",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 60,
    textAreaHeight: 30,
    referenceGap: 16,
  },
  transition: {
    type: "slide",
    duration: 300,
    easing: "ease-out",
    direction: "up",
  },
}

const LOWER_THIRD_GLASS: BroadcastTheme = {
  ...baseTheme,
  id: "builtin-lower-third-glass",
  name: "Lower Third Glass",
  category: "overlay",
  background: {
    type: "transparent",
    color: "transparent",
    gradient: null,
    image: null,
    video: null,
  },
  textBox: {
    enabled: true,
    color: "#1e293b",
    opacity: 0.6,
    borderRadius: 16,
    padding: 28,
  },
  verseText: {
    fontFamily: "Geist Variable",
    fontSize: 58,
    fontWeight: 500,
    color: "#f1f5f9",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    lineHeight: 1.5,
    letterSpacing: 0,
    shadow: { color: "rgba(0,0,0,0.5)", blur: 6, x: 0, y: 2 },
    outline: null,
  },
  verseNumbers: {
    visible: false,
    fontSize: 14,
    color: "#f1f5f9",
    superscript: true,
  },
  reference: {
    fontFamily: "Geist Variable",
    fontSize: 38,
    fontWeight: 500,
    color: "#93c5fd",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    uppercase: false,
    letterSpacing: 1,
    lineHeight: 1.4,
    position: "below",
    shadow: null,
    outline: null,
  },
  layout: {
    anchor: "bottom-center",
    offsetX: 0,
    offsetY: -5,
    padding: { top: 24, right: 48, bottom: 24, left: 48 },
    textAlign: "center",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 70,
    textAreaHeight: 30,
    referenceGap: 20,
  },
  transition: {
    type: "fade",
    duration: 350,
    easing: "ease-in-out",
    direction: "up",
  },
}

// ── Countdown themes ──
// Full themes like any other (background + decorative layers + backing box +
// layout), but categorised `countdown` and tuned so the timer digits — rendered
// via `timerStyle` in the verse region — read big and clean. These are what the
// countdown editor's Theme picker lists.

const COUNTDOWN_MIDNIGHT: BroadcastTheme = {
  ...baseTheme,
  id: "builtin-countdown-midnight",
  name: "Countdown Midnight",
  category: "countdown",
  background: {
    type: "gradient",
    color: "#0f0c29",
    gradient: {
      type: "radial",
      angle: 0,
      stops: [
        { color: "#302b63", position: 0 },
        { color: "#0f0c29", position: 100 },
      ],
    },
    image: null,
    video: null,
  },
  textBox: {
    enabled: false,
    color: "#000000",
    opacity: 0,
    borderRadius: 0,
    padding: 0,
  },
  verseText: {
    fontFamily: "Geist Variable",
    fontSize: 320,
    fontWeight: 700,
    color: "#ffffff",
    horizontalAlign: "center",
    verticalAlign: "middle",
    textTransform: "none",
    textDecoration: "none",
    lineHeight: 1,
    letterSpacing: 0,
    shadow: { color: "rgba(96,165,250,0.35)", blur: 60, x: 0, y: 0 },
    outline: null,
  },
  verseNumbers: {
    visible: false,
    fontSize: 16,
    color: "#ffffff",
    superscript: true,
  },
  reference: {
    fontFamily: "Geist Variable",
    fontSize: 56,
    fontWeight: 500,
    color: "#a78bfa",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "uppercase",
    textDecoration: "none",
    uppercase: true,
    letterSpacing: 8,
    lineHeight: 1.4,
    position: "above",
    shadow: null,
    outline: null,
  },
  layout: {
    anchor: "center",
    offsetX: 0,
    offsetY: 0,
    padding: { top: 40, right: 80, bottom: 40, left: 80 },
    textAlign: "center",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 90,
    textAreaHeight: 70,
    referenceGap: 48,
  },
  transition: {
    type: "fade",
    duration: 400,
    easing: "ease-in-out",
    direction: "up",
  },
}

const COUNTDOWN_MINIMAL: BroadcastTheme = {
  ...baseTheme,
  id: "builtin-countdown-minimal",
  name: "Countdown Minimal",
  category: "countdown",
  background: {
    type: "solid",
    color: "#0a0a0a",
    gradient: null,
    image: null,
    video: null,
  },
  textBox: {
    enabled: false,
    color: "#000000",
    opacity: 0,
    borderRadius: 0,
    padding: 0,
  },
  verseText: {
    fontFamily: "Geist Variable",
    fontSize: 300,
    fontWeight: 300,
    color: "#fafafa",
    horizontalAlign: "center",
    verticalAlign: "middle",
    textTransform: "none",
    textDecoration: "none",
    lineHeight: 1,
    letterSpacing: 4,
    shadow: null,
    outline: null,
  },
  verseNumbers: {
    visible: false,
    fontSize: 16,
    color: "#fafafa",
    superscript: true,
  },
  reference: {
    fontFamily: "Geist Variable",
    fontSize: 44,
    fontWeight: 400,
    color: "#71717a",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "uppercase",
    textDecoration: "none",
    uppercase: true,
    letterSpacing: 10,
    lineHeight: 1.4,
    position: "below",
    shadow: null,
    outline: null,
  },
  layout: {
    anchor: "center",
    offsetX: 0,
    offsetY: 0,
    padding: { top: 40, right: 80, bottom: 40, left: 80 },
    textAlign: "center",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 90,
    textAreaHeight: 70,
    referenceGap: 40,
  },
  transition: {
    type: "fade",
    duration: 300,
    easing: "ease-in-out",
    direction: "up",
  },
}

export const BUILTIN_THEMES: BroadcastTheme[] = [
  CLASSIC_DARK,
  MODERN_LIGHT,
  BROADCAST_OVERLAY,
  WORSHIP_NIGHT,
  HYMNAL,
  PRAISE_BOLD,
  PARCHMENT,
  SCRIPTURE_FOCUS,
  SERMON_CLEAN,
  SERMON_FULLSCREEN,
  LOWER_THIRD_DARK,
  LOWER_THIRD_GLASS,
  COUNTDOWN_MIDNIGHT,
  COUNTDOWN_MINIMAL,
]
