import type {
  SlideTheme,
  SlideThemeElement,
  AnimatedBackground,
} from "@/types/slide"

/**
 * Factory for the built-in animated song themes. Each is a `content-only` +
 * `blank` variant pair sharing one {@link AnimatedBackground} spec, so
 * `generateSlidesFromSong` bakes the animated background onto every slide. The
 * lyric text carries a soft glow tuned to the palette.
 */
function makeAnimatedSongTheme(t: {
  id: string
  name: string
  animated: AnimatedBackground
  textColor: string
  glow: string
  fontFamily?: string
}): SlideTheme {
  const lyric: SlideThemeElement = {
    type: "text",
    text: "Verse lyrics here",
    x: 5,
    y: 15,
    width: 90,
    height: 70,
    fontFamily: t.fontFamily ?? "Inter",
    fontSize: 52,
    fontWeight: 600,
    bold: false,
    italic: false,
    underline: false,
    color: t.textColor,
    horizontalAlign: "center",
    verticalAlign: "middle",
    lineHeight: 1.4,
    textTransform: "none",
    shadow: { offsetX: 0, offsetY: 0, blur: 24, color: t.glow },
    textBuild: {
      type: "line-by-line",
      duration: 320,
      delay: 0,
      reveal: "fade-up",
    },
  }
  return {
    id: t.id,
    name: t.name,
    category: "song",
    builtin: true,
    variants: [
      {
        layout: "content-only",
        background: { type: "animated", animated: t.animated },
        elements: [lyric],
      },
      {
        layout: "blank",
        background: { type: "animated", animated: t.animated },
        elements: [],
      },
    ],
  }
}

export const ANIMATED_SONG_THEMES: SlideTheme[] = [
  makeAnimatedSongTheme({
    id: "theme-aurora-worship",
    name: "Aurora Worship",
    animated: {
      preset: "aurora",
      palette: ["#4c1d95", "#1e3a8a", "#0ea5e9"],
      speed: 1,
      intensity: 0.6,
      baseColor: "#0b1020",
    },
    textColor: "#f0f9ff",
    glow: "rgba(14,165,233,0.45)",
  }),
  makeAnimatedSongTheme({
    id: "theme-golden-bokeh",
    name: "Golden Bokeh",
    animated: {
      preset: "bokeh",
      palette: ["#f59e0b", "#fbbf24", "#fde68a"],
      speed: 0.8,
      intensity: 0.7,
      baseColor: "#1a1206",
    },
    textColor: "#fffbeb",
    glow: "rgba(251,191,36,0.4)",
  }),
  makeAnimatedSongTheme({
    id: "theme-ember-glow",
    name: "Ember Glow",
    animated: {
      preset: "embers",
      palette: ["#f97316", "#ef4444", "#fbbf24"],
      speed: 1,
      intensity: 0.7,
      baseColor: "#1a0a05",
    },
    textColor: "#fff7ed",
    glow: "rgba(249,115,22,0.45)",
  }),
  makeAnimatedSongTheme({
    id: "theme-starry-host",
    name: "Starry Host",
    animated: {
      preset: "starfield",
      palette: ["#e0e7ff", "#a5b4fc", "#c7d2fe"],
      speed: 1,
      intensity: 0.8,
      baseColor: "#060814",
    },
    textColor: "#eef2ff",
    glow: "rgba(165,180,252,0.4)",
  }),
  makeAnimatedSongTheme({
    id: "theme-silent-night",
    name: "Silent Night",
    animated: {
      preset: "snow",
      palette: ["#e0f2fe", "#bae6fd", "#f0f9ff"],
      speed: 0.9,
      intensity: 0.7,
      baseColor: "#0b1a2b",
    },
    textColor: "#f8fafc",
    glow: "rgba(186,230,253,0.4)",
  }),
  makeAnimatedSongTheme({
    id: "theme-light-of-the-world",
    name: "Light of the World",
    animated: {
      preset: "godrays",
      palette: ["#fde68a", "#fca5a5", "#fef3c7"],
      speed: 0.8,
      intensity: 0.7,
      baseColor: "#12100a",
    },
    textColor: "#fffdf5",
    glow: "rgba(253,230,138,0.45)",
  }),
  makeAnimatedSongTheme({
    id: "theme-flowing-grace",
    name: "Flowing Grace",
    animated: {
      preset: "gradient-drift",
      palette: ["#0f766e", "#1e3a8a", "#6d28d9"],
      speed: 0.7,
      intensity: 0.9,
      baseColor: "#050b12",
    },
    textColor: "#f0fdfa",
    glow: "rgba(45,212,191,0.4)",
  }),
]

export const BUILTIN_SLIDE_THEMES: SlideTheme[] = [
  {
    id: "theme-midnight",
    name: "Midnight",
    category: "general",
    builtin: true,
    variants: [
      {
        layout: "title",
        background: {
          type: "gradient",
          gradient: {
            type: "linear",
            angle: 135,
            stops: [
              { offset: 0, color: "#0f0c29" },
              { offset: 0.5, color: "#302b63" },
              { offset: 1, color: "#24243e" },
            ],
          },
        },
        elements: [
          {
            type: "text",
            text: "Title",
            x: 10,
            y: 30,
            width: 80,
            height: 20,
            fontFamily: "Inter",
            fontSize: 64,
            fontWeight: 700,
            bold: true,
            italic: false,
            underline: false,
            color: "#ffffff",
            horizontalAlign: "center",
            verticalAlign: "middle",
            lineHeight: 1.2,
            textTransform: "none",
          },
          {
            type: "text",
            text: "Subtitle",
            x: 20,
            y: 55,
            width: 60,
            height: 12,
            fontFamily: "Inter",
            fontSize: 28,
            fontWeight: 400,
            bold: false,
            italic: false,
            underline: false,
            color: "#a5b4fc",
            horizontalAlign: "center",
            verticalAlign: "middle",
            lineHeight: 1.4,
            textTransform: "none",
          },
        ],
      },
      {
        layout: "title-content",
        background: {
          type: "gradient",
          gradient: {
            type: "linear",
            angle: 135,
            stops: [
              { offset: 0, color: "#0f0c29" },
              { offset: 0.5, color: "#302b63" },
              { offset: 1, color: "#24243e" },
            ],
          },
        },
        elements: [
          {
            type: "text",
            text: "Title",
            x: 5,
            y: 5,
            width: 90,
            height: 15,
            fontFamily: "Inter",
            fontSize: 48,
            fontWeight: 700,
            bold: true,
            italic: false,
            underline: false,
            color: "#ffffff",
            horizontalAlign: "left",
            verticalAlign: "middle",
            lineHeight: 1.2,
            textTransform: "none",
          },
          {
            type: "text",
            text: "Content goes here",
            x: 5,
            y: 25,
            width: 90,
            height: 65,
            fontFamily: "Inter",
            fontSize: 32,
            fontWeight: 400,
            bold: false,
            italic: false,
            underline: false,
            color: "#e2e8f0",
            horizontalAlign: "left",
            verticalAlign: "top",
            lineHeight: 1.5,
            textTransform: "none",
          },
        ],
      },
      {
        layout: "content-only",
        background: {
          type: "gradient",
          gradient: {
            type: "linear",
            angle: 135,
            stops: [
              { offset: 0, color: "#0f0c29" },
              { offset: 0.5, color: "#302b63" },
              { offset: 1, color: "#24243e" },
            ],
          },
        },
        elements: [
          {
            type: "text",
            text: "Content goes here",
            x: 10,
            y: 10,
            width: 80,
            height: 80,
            fontFamily: "Inter",
            fontSize: 36,
            fontWeight: 400,
            bold: false,
            italic: false,
            underline: false,
            color: "#ffffff",
            horizontalAlign: "center",
            verticalAlign: "middle",
            lineHeight: 1.5,
            textTransform: "none",
          },
        ],
      },
      {
        layout: "blank",
        background: {
          type: "gradient",
          gradient: {
            type: "linear",
            angle: 135,
            stops: [
              { offset: 0, color: "#0f0c29" },
              { offset: 0.5, color: "#302b63" },
              { offset: 1, color: "#24243e" },
            ],
          },
        },
        elements: [],
      },
    ],
  },
  {
    id: "theme-warm-glow",
    name: "Warm Glow",
    category: "general",
    builtin: true,
    variants: [
      {
        layout: "title",
        background: {
          type: "gradient",
          gradient: {
            type: "radial",
            stops: [
              { offset: 0, color: "#92400e" },
              { offset: 1, color: "#451a03" },
            ],
          },
        },
        elements: [
          {
            type: "text",
            text: "Title",
            x: 10,
            y: 30,
            width: 80,
            height: 20,
            fontFamily: "Georgia",
            fontSize: 64,
            fontWeight: 700,
            bold: true,
            italic: false,
            underline: false,
            color: "#fef3c7",
            horizontalAlign: "center",
            verticalAlign: "middle",
            lineHeight: 1.2,
            textTransform: "none",
          },
          {
            type: "text",
            text: "Subtitle",
            x: 20,
            y: 55,
            width: 60,
            height: 12,
            fontFamily: "Georgia",
            fontSize: 28,
            fontWeight: 400,
            bold: false,
            italic: true,
            underline: false,
            color: "#fbbf24",
            horizontalAlign: "center",
            verticalAlign: "middle",
            lineHeight: 1.4,
            textTransform: "none",
          },
        ],
      },
      {
        layout: "content-only",
        background: {
          type: "gradient",
          gradient: {
            type: "radial",
            stops: [
              { offset: 0, color: "#92400e" },
              { offset: 1, color: "#451a03" },
            ],
          },
        },
        elements: [
          {
            type: "text",
            text: "Content",
            x: 10,
            y: 10,
            width: 80,
            height: 80,
            fontFamily: "Georgia",
            fontSize: 36,
            fontWeight: 400,
            bold: false,
            italic: false,
            underline: false,
            color: "#fef3c7",
            horizontalAlign: "center",
            verticalAlign: "middle",
            lineHeight: 1.5,
            textTransform: "none",
          },
        ],
      },
      {
        layout: "blank",
        background: {
          type: "gradient",
          gradient: {
            type: "radial",
            stops: [
              { offset: 0, color: "#92400e" },
              { offset: 1, color: "#451a03" },
            ],
          },
        },
        elements: [],
      },
    ],
  },
  {
    id: "theme-ocean",
    name: "Ocean Deep",
    category: "general",
    builtin: true,
    variants: [
      {
        layout: "title",
        background: {
          type: "gradient",
          gradient: {
            type: "linear",
            angle: 180,
            stops: [
              { offset: 0, color: "#0c4a6e" },
              { offset: 1, color: "#082f49" },
            ],
          },
        },
        elements: [
          {
            type: "text",
            text: "Title",
            x: 10,
            y: 30,
            width: 80,
            height: 20,
            fontFamily: "Inter",
            fontSize: 64,
            fontWeight: 700,
            bold: true,
            italic: false,
            underline: false,
            color: "#e0f2fe",
            horizontalAlign: "center",
            verticalAlign: "middle",
            lineHeight: 1.2,
            textTransform: "none",
          },
          {
            type: "text",
            text: "Subtitle",
            x: 20,
            y: 55,
            width: 60,
            height: 12,
            fontFamily: "Inter",
            fontSize: 28,
            fontWeight: 400,
            bold: false,
            italic: false,
            underline: false,
            color: "#7dd3fc",
            horizontalAlign: "center",
            verticalAlign: "middle",
            lineHeight: 1.4,
            textTransform: "none",
          },
        ],
      },
      {
        layout: "content-only",
        background: {
          type: "gradient",
          gradient: {
            type: "linear",
            angle: 180,
            stops: [
              { offset: 0, color: "#0c4a6e" },
              { offset: 1, color: "#082f49" },
            ],
          },
        },
        elements: [
          {
            type: "text",
            text: "Content",
            x: 10,
            y: 10,
            width: 80,
            height: 80,
            fontFamily: "Inter",
            fontSize: 36,
            fontWeight: 400,
            bold: false,
            italic: false,
            underline: false,
            color: "#e0f2fe",
            horizontalAlign: "center",
            verticalAlign: "middle",
            lineHeight: 1.5,
            textTransform: "none",
          },
        ],
      },
      {
        layout: "blank",
        background: {
          type: "gradient",
          gradient: {
            type: "linear",
            angle: 180,
            stops: [
              { offset: 0, color: "#0c4a6e" },
              { offset: 1, color: "#082f49" },
            ],
          },
        },
        elements: [],
      },
    ],
  },
  {
    id: "theme-forest",
    name: "Forest",
    category: "general",
    builtin: true,
    variants: [
      {
        layout: "title",
        background: {
          type: "gradient",
          gradient: {
            type: "linear",
            angle: 160,
            stops: [
              { offset: 0, color: "#14532d" },
              { offset: 1, color: "#052e16" },
            ],
          },
        },
        elements: [
          {
            type: "text",
            text: "Title",
            x: 10,
            y: 30,
            width: 80,
            height: 20,
            fontFamily: "Georgia",
            fontSize: 64,
            fontWeight: 700,
            bold: true,
            italic: false,
            underline: false,
            color: "#dcfce7",
            horizontalAlign: "center",
            verticalAlign: "middle",
            lineHeight: 1.2,
            textTransform: "none",
          },
          {
            type: "text",
            text: "Subtitle",
            x: 20,
            y: 55,
            width: 60,
            height: 12,
            fontFamily: "Georgia",
            fontSize: 28,
            fontWeight: 400,
            bold: false,
            italic: false,
            underline: false,
            color: "#86efac",
            horizontalAlign: "center",
            verticalAlign: "middle",
            lineHeight: 1.4,
            textTransform: "none",
          },
        ],
      },
      {
        layout: "content-only",
        background: {
          type: "gradient",
          gradient: {
            type: "linear",
            angle: 160,
            stops: [
              { offset: 0, color: "#14532d" },
              { offset: 1, color: "#052e16" },
            ],
          },
        },
        elements: [
          {
            type: "text",
            text: "Content",
            x: 10,
            y: 10,
            width: 80,
            height: 80,
            fontFamily: "Georgia",
            fontSize: 36,
            fontWeight: 400,
            bold: false,
            italic: false,
            underline: false,
            color: "#dcfce7",
            horizontalAlign: "center",
            verticalAlign: "middle",
            lineHeight: 1.5,
            textTransform: "none",
          },
        ],
      },
      {
        layout: "blank",
        background: {
          type: "gradient",
          gradient: {
            type: "linear",
            angle: 160,
            stops: [
              { offset: 0, color: "#14532d" },
              { offset: 1, color: "#052e16" },
            ],
          },
        },
        elements: [],
      },
    ],
  },
  {
    id: "theme-clean-white",
    name: "Clean White",
    category: "general",
    builtin: true,
    variants: [
      {
        layout: "title",
        background: { type: "solid", color: "#ffffff" },
        elements: [
          {
            type: "text",
            text: "Title",
            x: 10,
            y: 30,
            width: 80,
            height: 20,
            fontFamily: "Inter",
            fontSize: 64,
            fontWeight: 700,
            bold: true,
            italic: false,
            underline: false,
            color: "#1e293b",
            horizontalAlign: "center",
            verticalAlign: "middle",
            lineHeight: 1.2,
            textTransform: "none",
          },
          {
            type: "text",
            text: "Subtitle",
            x: 20,
            y: 55,
            width: 60,
            height: 12,
            fontFamily: "Inter",
            fontSize: 28,
            fontWeight: 400,
            bold: false,
            italic: false,
            underline: false,
            color: "#64748b",
            horizontalAlign: "center",
            verticalAlign: "middle",
            lineHeight: 1.4,
            textTransform: "none",
          },
        ],
      },
      {
        layout: "content-only",
        background: { type: "solid", color: "#ffffff" },
        elements: [
          {
            type: "text",
            text: "Content",
            x: 10,
            y: 10,
            width: 80,
            height: 80,
            fontFamily: "Inter",
            fontSize: 36,
            fontWeight: 400,
            bold: false,
            italic: false,
            underline: false,
            color: "#1e293b",
            horizontalAlign: "center",
            verticalAlign: "middle",
            lineHeight: 1.5,
            textTransform: "none",
          },
        ],
      },
      {
        layout: "blank",
        background: { type: "solid", color: "#ffffff" },
        elements: [],
      },
    ],
  },
  {
    id: "theme-worship-lyrics",
    name: "Worship Lyrics",
    category: "song",
    builtin: true,
    variants: [
      {
        layout: "content-only",
        background: { type: "solid", color: "#000000" },
        elements: [
          {
            type: "text",
            text: "Verse lyrics here",
            x: 5,
            y: 15,
            width: 90,
            height: 70,
            fontFamily: "Inter",
            fontSize: 52,
            fontWeight: 700,
            bold: true,
            italic: false,
            underline: false,
            color: "#ffffff",
            horizontalAlign: "center",
            verticalAlign: "middle",
            lineHeight: 1.4,
            textTransform: "none",
          },
        ],
      },
      {
        layout: "blank",
        background: { type: "solid", color: "#000000" },
        elements: [],
      },
    ],
  },
  {
    id: "theme-lyric-glow",
    name: "Lyric Glow",
    category: "song",
    builtin: true,
    variants: [
      {
        layout: "content-only",
        background: {
          type: "gradient",
          gradient: {
            type: "radial",
            stops: [
              { offset: 0, color: "#1e1b4b" },
              { offset: 1, color: "#0f172a" },
            ],
          },
        },
        elements: [
          {
            type: "text",
            text: "Verse lyrics here",
            x: 5,
            y: 15,
            width: 90,
            height: 70,
            fontFamily: "Inter",
            fontSize: 52,
            fontWeight: 600,
            bold: false,
            italic: false,
            underline: false,
            color: "#e0e7ff",
            horizontalAlign: "center",
            verticalAlign: "middle",
            lineHeight: 1.4,
            textTransform: "none",
            shadow: {
              offsetX: 0,
              offsetY: 0,
              blur: 20,
              color: "rgba(99,102,241,0.5)",
            },
          },
        ],
      },
      {
        layout: "blank",
        background: {
          type: "gradient",
          gradient: {
            type: "radial",
            stops: [
              { offset: 0, color: "#1e1b4b" },
              { offset: 1, color: "#0f172a" },
            ],
          },
        },
        elements: [],
      },
    ],
  },
  {
    id: "theme-hymnal",
    name: "Hymnal",
    category: "song",
    builtin: true,
    variants: [
      {
        layout: "content-only",
        background: { type: "solid", color: "#1c1917" },
        elements: [
          {
            type: "text",
            text: "Verse lyrics here",
            x: 10,
            y: 10,
            width: 80,
            height: 70,
            fontFamily: "Georgia",
            fontSize: 48,
            fontWeight: 400,
            bold: false,
            italic: false,
            underline: false,
            color: "#fef3c7",
            horizontalAlign: "center",
            verticalAlign: "middle",
            lineHeight: 1.5,
            textTransform: "none",
          },
          {
            type: "text",
            text: "— Hymn Title",
            x: 20,
            y: 82,
            width: 60,
            height: 10,
            fontFamily: "Georgia",
            fontSize: 24,
            fontWeight: 400,
            bold: false,
            italic: true,
            underline: false,
            color: "#a8a29e",
            horizontalAlign: "center",
            verticalAlign: "middle",
            lineHeight: 1.4,
            textTransform: "none",
          },
        ],
      },
      {
        layout: "blank",
        background: { type: "solid", color: "#1c1917" },
        elements: [],
      },
    ],
  },
  {
    id: "theme-scripture-classic",
    name: "Scripture Classic",
    category: "scripture",
    builtin: true,
    variants: [
      {
        layout: "scripture",
        background: {
          type: "gradient",
          gradient: {
            type: "linear",
            angle: 180,
            stops: [
              { offset: 0, color: "#1e293b" },
              { offset: 1, color: "#0f172a" },
            ],
          },
        },
        elements: [
          {
            type: "scripture",
            reference: "John 3:16",
            verseText: "For God so loved the world...",
            translation: "KJV",
            x: 10,
            y: 15,
            width: 80,
            height: 65,
            fontFamily: "Georgia",
            fontSize: 42,
            fontWeight: 400,
            bold: false,
            italic: false,
            color: "#f1f5f9",
            horizontalAlign: "center",
            verticalAlign: "middle",
            lineHeight: 1.6,
            referenceFontSize: 24,
            referenceColor: "#94a3b8",
          },
        ],
      },
      {
        layout: "blank",
        background: {
          type: "gradient",
          gradient: {
            type: "linear",
            angle: 180,
            stops: [
              { offset: 0, color: "#1e293b" },
              { offset: 1, color: "#0f172a" },
            ],
          },
        },
        elements: [],
      },
    ],
  },
  {
    id: "theme-scripture-warm",
    name: "Scripture Warm",
    category: "scripture",
    builtin: true,
    variants: [
      {
        layout: "scripture",
        background: {
          type: "gradient",
          gradient: {
            type: "radial",
            stops: [
              { offset: 0, color: "#78350f" },
              { offset: 1, color: "#431407" },
            ],
          },
        },
        elements: [
          {
            type: "scripture",
            reference: "Psalm 23:1",
            verseText: "The LORD is my shepherd...",
            translation: "KJV",
            x: 10,
            y: 15,
            width: 80,
            height: 65,
            fontFamily: "Georgia",
            fontSize: 42,
            fontWeight: 400,
            bold: false,
            italic: false,
            color: "#fef3c7",
            horizontalAlign: "center",
            verticalAlign: "middle",
            lineHeight: 1.6,
            referenceFontSize: 24,
            referenceColor: "#fbbf24",
          },
        ],
      },
      {
        layout: "blank",
        background: {
          type: "gradient",
          gradient: {
            type: "radial",
            stops: [
              { offset: 0, color: "#78350f" },
              { offset: 1, color: "#431407" },
            ],
          },
        },
        elements: [],
      },
    ],
  },
  {
    id: "theme-ember",
    name: "Ember",
    category: "general",
    builtin: true,
    variants: [
      {
        layout: "title",
        background: {
          type: "gradient",
          gradient: {
            type: "linear",
            angle: 135,
            stops: [
              { offset: 0, color: "#7f1d1d" },
              { offset: 0.5, color: "#991b1b" },
              { offset: 1, color: "#450a0a" },
            ],
          },
        },
        elements: [
          {
            type: "text",
            text: "Title",
            x: 10,
            y: 30,
            width: 80,
            height: 20,
            fontFamily: "Inter",
            fontSize: 64,
            fontWeight: 700,
            bold: true,
            italic: false,
            underline: false,
            color: "#fecaca",
            horizontalAlign: "center",
            verticalAlign: "middle",
            lineHeight: 1.2,
            textTransform: "none",
          },
          {
            type: "text",
            text: "Subtitle",
            x: 20,
            y: 55,
            width: 60,
            height: 12,
            fontFamily: "Inter",
            fontSize: 28,
            fontWeight: 400,
            bold: false,
            italic: false,
            underline: false,
            color: "#f87171",
            horizontalAlign: "center",
            verticalAlign: "middle",
            lineHeight: 1.4,
            textTransform: "none",
          },
        ],
      },
      {
        layout: "content-only",
        background: {
          type: "gradient",
          gradient: {
            type: "linear",
            angle: 135,
            stops: [
              { offset: 0, color: "#7f1d1d" },
              { offset: 0.5, color: "#991b1b" },
              { offset: 1, color: "#450a0a" },
            ],
          },
        },
        elements: [
          {
            type: "text",
            text: "Content",
            x: 10,
            y: 10,
            width: 80,
            height: 80,
            fontFamily: "Inter",
            fontSize: 36,
            fontWeight: 400,
            bold: false,
            italic: false,
            underline: false,
            color: "#fecaca",
            horizontalAlign: "center",
            verticalAlign: "middle",
            lineHeight: 1.5,
            textTransform: "none",
          },
        ],
      },
      {
        layout: "blank",
        background: {
          type: "gradient",
          gradient: {
            type: "linear",
            angle: 135,
            stops: [
              { offset: 0, color: "#7f1d1d" },
              { offset: 0.5, color: "#991b1b" },
              { offset: 1, color: "#450a0a" },
            ],
          },
        },
        elements: [],
      },
    ],
  },
  {
    id: "theme-royal-purple",
    name: "Royal Purple",
    category: "general",
    builtin: true,
    variants: [
      {
        layout: "title",
        background: {
          type: "gradient",
          gradient: {
            type: "linear",
            angle: 160,
            stops: [
              { offset: 0, color: "#581c87" },
              { offset: 1, color: "#3b0764" },
            ],
          },
        },
        elements: [
          {
            type: "text",
            text: "Title",
            x: 10,
            y: 30,
            width: 80,
            height: 20,
            fontFamily: "Inter",
            fontSize: 64,
            fontWeight: 700,
            bold: true,
            italic: false,
            underline: false,
            color: "#f5d0fe",
            horizontalAlign: "center",
            verticalAlign: "middle",
            lineHeight: 1.2,
            textTransform: "none",
          },
          {
            type: "text",
            text: "Subtitle",
            x: 20,
            y: 55,
            width: 60,
            height: 12,
            fontFamily: "Inter",
            fontSize: 28,
            fontWeight: 400,
            bold: false,
            italic: false,
            underline: false,
            color: "#d8b4fe",
            horizontalAlign: "center",
            verticalAlign: "middle",
            lineHeight: 1.4,
            textTransform: "none",
          },
        ],
      },
      {
        layout: "content-only",
        background: {
          type: "gradient",
          gradient: {
            type: "linear",
            angle: 160,
            stops: [
              { offset: 0, color: "#581c87" },
              { offset: 1, color: "#3b0764" },
            ],
          },
        },
        elements: [
          {
            type: "text",
            text: "Content",
            x: 10,
            y: 10,
            width: 80,
            height: 80,
            fontFamily: "Inter",
            fontSize: 36,
            fontWeight: 400,
            bold: false,
            italic: false,
            underline: false,
            color: "#f5d0fe",
            horizontalAlign: "center",
            verticalAlign: "middle",
            lineHeight: 1.5,
            textTransform: "none",
          },
        ],
      },
      {
        layout: "blank",
        background: {
          type: "gradient",
          gradient: {
            type: "linear",
            angle: 160,
            stops: [
              { offset: 0, color: "#581c87" },
              { offset: 1, color: "#3b0764" },
            ],
          },
        },
        elements: [],
      },
    ],
  },
  ...ANIMATED_SONG_THEMES,
]
